INSERT INTO Personal ( Tipo_personal, Cedula_profesional, Especialidad, Nombre_completo, Fecha_nacimiento, Fecha_ingreso, Numero_telefonico, Direccion, Turno, Horario, Salario_neto, RFC, CURP) VALUES ( 'Veterinario', 'CP12345678', 'Veterinaria', 'Juan Pérez', DATE '1975-06-15', TIMESTAMP '2023-05-01 09:00:00', '1234567890', 'Calle 123, Ciudad, País', 'Mañana', '9:00-17:00', 2000.00, 'RFC1234567890', 'CURP12345678901234');
INSERT INTO Personal ( Tipo_personal, Cedula_profesional, Especialidad, Nombre_completo, Fecha_nacimiento, Fecha_ingreso, Numero_telefonico, Direccion, Turno, Horario, Salario_neto, RFC, CURP) VALUES ( 'Asistente', 'CP23456789', 'Veterinaria', 'Ana Gómez', DATE '1985-07-25', TIMESTAMP '2023-05-01 13:00:00', '0987654321', 'Calle 456, Ciudad, País', 'Tarde', '13:00-21:00', 1500.00, 'RFC0987654321', 'CURP23456789012345');
INSERT INTO Personal ( Tipo_personal, Cedula_profesional, Especialidad, Nombre_completo, Fecha_nacimiento, Fecha_ingreso, Numero_telefonico, Direccion, Turno, Horario, Salario_neto, RFC, CURP) VALUES ( 'Administrativo', NULL, NULL, 'Pedro Martínez', DATE '1990-08-05', TIMESTAMP '2023-05-01 09:00:00', '1122334455', 'Calle 789, Ciudad, País', 'Mañana', '9:00-17:00', 1200.00, 'RFC1122334455', 'CURP34567890123456');
INSERT INTO Personal ( Tipo_personal, Cedula_profesional, Especialidad, Nombre_completo, Fecha_nacimiento, Fecha_ingreso, Numero_telefonico, Direccion, Turno, Horario, Salario_neto, RFC, CURP) VALUES ( 'Veterinario', 'CP34567890', 'Veterinaria', 'María Rodríguez', DATE '1980-09-15', TIMESTAMP '2023-05-01 13:00:00', '5566778899', 'Calle 012, Ciudad, País', 'Tarde', '13:00-21:00', 2000.00, 'RFC5566778899', 'CURP45678901234567');
INSERT INTO Personal ( Tipo_personal, Cedula_profesional, Especialidad, Nombre_completo, Fecha_nacimiento, Fecha_ingreso, Numero_telefonico, Direccion, Turno, Horario, Salario_neto, RFC, CURP) VALUES ( 'Asistente', 'CP45678901', 'Veterinaria', 'José Hernández', DATE '1995-10-25', TIMESTAMP '2023-05-01 09:00:00', '9988776655', 'Calle 345, Ciudad, País', 'Mañana', '9:00-17:00', 1500.00, 'RFC9988776655', 'CURP56789012345678');

INSERT INTO Nomina ( ID_personal, Fecha_pago, Tipo_pago, Horas_trabajadas, Horas_extras, Retardos, Faltas, Empleado_del_mes, Salario_total) VALUES ( 1, TIMESTAMP '2023-05-31 20:00:00', 'Depósito', 160, 0, 0, 0, 1, 2000.00);
INSERT INTO Nomina ( ID_personal, Fecha_pago, Tipo_pago, Horas_trabajadas, Horas_extras, Retardos, Faltas, Empleado_del_mes, Salario_total) VALUES ( 2, TIMESTAMP '2023-05-31 20:00:00', 'Depósito', 160, 5, 1, 0, 0, 1543.75);
INSERT INTO Nomina ( ID_personal, Fecha_pago, Tipo_pago, Horas_trabajadas, Horas_extras, Retardos, Faltas, Empleado_del_mes, Salario_total) VALUES ( 3, TIMESTAMP '2023-05-31 20:00:00', 'Depósito', 160, 0, 0, 1, 0, 1187.50);
INSERT INTO Nomina ( ID_personal, Fecha_pago, Tipo_pago, Horas_trabajadas, Horas_extras, Retardos, Faltas, Empleado_del_mes, Salario_total) VALUES ( 4, TIMESTAMP '2023-05-31 20:00:00', 'Depósito', 160, 10, 0, 0, 0, 2187.50);
INSERT INTO Nomina ( ID_personal, Fecha_pago, Tipo_pago, Horas_trabajadas, Horas_extras, Retardos, Faltas, Empleado_del_mes, Salario_total) VALUES ( 5, TIMESTAMP '2023-05-31 20:00:00', 'Depósito', 160, 0, 2, 0, 0, 1462.50);

INSERT INTO Propietarios ( Nombre, Apellido, Telefono, Direccion, Numero_cliente, Correo_electronico) VALUES ( 'Laura', 'Ramírez', '1234567890', 'Calle 123, Ciudad, País', 1, 'laura.ramirez@email.com');
INSERT INTO Propietarios ( Nombre, Apellido, Telefono, Direccion, Numero_cliente, Correo_electronico) VALUES ( 'Carlos', 'García', '0987654321', 'Calle 456, Ciudad, País', 2, 'carlos.garcia@email.com');
INSERT INTO Propietarios ( Nombre, Apellido, Telefono, Direccion, Numero_cliente, Correo_electronico) VALUES ( 'Fernanda', 'López', '1122334455', 'Calle 789, Ciudad, País', 3, 'fernanda.lopez@email.com');
INSERT INTO Propietarios ( Nombre, Apellido, Telefono, Direccion, Numero_cliente, Correo_electronico) VALUES ( 'Sergio', 'Morales', '5566778899', 'Calle 012, Ciudad, País', 4, 'sergio.morales@email.com');
INSERT INTO Propietarios ( Nombre, Apellido, Telefono, Direccion, Numero_cliente, Correo_electronico) VALUES ('Valentina', 'Ortega', '9988776655', 'Calle 345, Ciudad, País', 5, 'valentina.ortega@email.com');

INSERT INTO Proveedores (Nombre, Direccion, Telefono, Articulos_que_provee) VALUES ('Proveedor Médico SA', 'Calle 123, Ciudad, País', '123-456-7890', 'Medicamentos, equipos médicos, suministros veterinarios');
INSERT INTO Proveedores (Nombre, Direccion, Telefono, Articulos_que_provee) VALUES ('Equipos Veterinarios Ltda.', 'Calle 456, Ciudad, País', '234-567-8901', 'Equipos médicos, suministros veterinarios');
INSERT INTO Proveedores (Nombre, Direccion, Telefono, Articulos_que_provee) VALUES ('Alimentos para Mascotas Corp.', 'Calle 789, Ciudad, País', '345-678-9012', 'Alimentos para perros, alimentos para gatos');
INSERT INTO Proveedores (Nombre, Direccion, Telefono, Articulos_que_provee) VALUES ('Farmacia Veterinaria ABC', 'Calle 321, Ciudad, País', '456-789-0123', 'Medicamentos, suministros veterinarios');
INSERT INTO Proveedores (Nombre, Direccion, Telefono, Articulos_que_provee) VALUES ('Productos de Higiene para Mascotas XYZ', 'Calle 654, Ciudad, País', '567-890-1234', 'Shampoo para mascotas, cepillos, productos de limpieza');

INSERT INTO Expedientes ( ID_propietario, Nombre_mascota, Edad, Sexo, Raza, Color, Historial_clinico, Cirugias, Tratamientos, Fecha_ingreso, Fecha_egreso, Diagnostico, Esquema_vacunacion, Alergias) VALUES (1, 'Fido', 5, 'M', 'Labrador', 'Amarillo', 'Vacunas al día, sin enfermedades previas', NULL, NULL, TIMESTAMP '2023-05-11 10:00:00', TIMESTAMP '2023-05-11 11:30:00', 'Revisión rutinaria', 'Vacunas al día', NULL);
INSERT INTO Expedientes ( ID_propietario, Nombre_mascota, Edad, Sexo, Raza, Color, Historial_clinico, Cirugias, Tratamientos, Fecha_ingreso, Fecha_egreso, Diagnostico, Esquema_vacunacion, Alergias) VALUES (2, 'Luna', 3, 'H', 'Pastor Alemán', 'Negro y fuego', 'Vacunas al día, sin enfermedades previas', NULL, NULL, TIMESTAMP '2023-05-11 14:00:00', TIMESTAMP '2023-05-11 15:00:00', 'Revisión rutinaria', 'Vacunas al día', NULL);
INSERT INTO Expedientes ( ID_propietario, Nombre_mascota, Edad, Sexo, Raza, Color, Historial_clinico, Cirugias, Tratamientos, Fecha_ingreso, Fecha_egreso, Diagnostico, Esquema_vacunacion, Alergias) VALUES (3, 'Toby', 7, 'M', 'Bulldog Inglés', 'Blanco y atigrado', 'Vacunas al día, tratamiento previo para displasia de cadera', 'Cirugía de cadera', 'Tratamiento para displasia de cadera', TIMESTAMP '2023-05-12 10:30:00', TIMESTAMP '2023-05-12 12:00:00', 'Control postoperatorio', 'Vacunas al día', 'Alergia a ciertos alimentos');
INSERT INTO Expedientes ( ID_propietario, Nombre_mascota, Edad, Sexo, Raza, Color, Historial_clinico, Cirugias, Tratamientos, Fecha_ingreso, Fecha_egreso, Diagnostico, Esquema_vacunacion, Alergias) VALUES (4, 'Bella', 2, 'H', 'Siames', 'Lynx Point', 'Vacunas al día, sin enfermedades previas', NULL, NULL, TIMESTAMP '2023-05-12 16:00:00', TIMESTAMP '2023-05-12 17:00:00', 'Revisión rutinaria', 'Vacunas al día', NULL);
INSERT INTO Expedientes (ID_propietario, Nombre_mascota, Edad, Sexo, Raza, Color, Historial_clinico, Cirugias, Tratamientos, Fecha_ingreso, Fecha_egreso, Diagnostico, Esquema_vacunacion, Alergias) VALUES (5, 'Rocky', 4, 'M', 'Poodle', 'Blanco', 'Vacunas al día, sin enfermedades previas', NULL, NULL, TIMESTAMP '2023-05-13 11:00:00', NULL, 'Revisión rutinaria', 'Vacunas al día', 'Sin alergias');

INSERT INTO Inventario ( ID_proveedor, Clasificacion, Nombre_producto, Caracteristicas, Precio_unitario, Cantidad_inventario, Fecha_caducidad, Productos_descuento, Marca_producto, Presentacion, Fecha_compra) VALUES (1, 'Medicamento', 'Antibiótico', 'Antibiótico para perros y gatos', 15, 200, TIMESTAMP '2024-12-31 00:00:00', 0, 'MarcaA', 'Caja de 20 tabletas', TIMESTAMP '2023-05-10 00:00:00');
INSERT INTO Inventario ( ID_proveedor, Clasificacion, Nombre_producto, Caracteristicas, Precio_unitario, Cantidad_inventario, Fecha_caducidad, Productos_descuento, Marca_producto, Presentacion, Fecha_compra) VALUES (1, 'Medicamento', 'Antiinflamatorio', 'Antiinflamatorio para perros y gatos', 10, 150, TIMESTAMP '2024-11-30 00:00:00', 0, 'MarcaA', 'Caja de 20 tabletas', TIMESTAMP '2023-05-10 00:00:00');
INSERT INTO Inventario ( ID_proveedor, Clasificacion, Nombre_producto, Caracteristicas, Precio_unitario, Cantidad_inventario, Fecha_caducidad, Productos_descuento, Marca_producto, Presentacion, Fecha_compra) VALUES (2, 'Equipo', 'Equipo de ultrasonido', 'Equipo de ultrasonido para uso veterinario', 5000, 5, NULL, 0, 'MarcaB', 'Unidad', TIMESTAMP '2023-04-01 00:00:00');
INSERT INTO Inventario ( ID_proveedor, Clasificacion, Nombre_producto, Caracteristicas, Precio_unitario, Cantidad_inventario, Fecha_caducidad, Productos_descuento, Marca_producto, Presentacion, Fecha_compra) VALUES (3, 'Alimento', 'Alimento para perros', 'Alimento para perros de todas las edades', 20, 500, TIMESTAMP '2023-12-31 00:00:00', 1, 'MarcaC', 'Bolsa de 1kg', TIMESTAMP '2023-05-01 00:00:00');
INSERT INTO Inventario ( ID_proveedor, Clasificacion, Nombre_producto, Caracteristicas, Precio_unitario, Cantidad_inventario, Fecha_caducidad, Productos_descuento, Marca_producto, Presentacion, Fecha_compra) VALUES (4, 'Medicamento', 'Vacuna antirrábica', 'Vacuna antirrábica para perros y gatos', 30, 100, TIMESTAMP '2024-10-31 00:00:00', 0, 'MarcaD', 'Vial individual', TIMESTAMP '2023-05-10 00:00:00');

INSERT INTO RecetasMedicas ( ID_mascota, ID_personal, Peso, Medicamentos_recetados, Indicaciones_generales, Fecha) VALUES (1, 1, 35, 'Antibiótico, Antiinflamatorio', 'Dar medicamentos después de las comidas', TIMESTAMP '2023-05-11 11:30:00');
INSERT INTO RecetasMedicas ( ID_mascota, ID_personal, Peso, Medicamentos_recetados, Indicaciones_generales, Fecha) VALUES (3, 2, 22, 'Analgésico, Suplemento para las articulaciones', 'Dar medicamentos después de las comidas', TIMESTAMP '2023-05-12 12:00:00');
INSERT INTO RecetasMedicas ( ID_mascota, ID_personal, Peso, Medicamentos_recetados, Indicaciones_generales, Fecha) VALUES (4, 1, 4, 'Vitamina, Suplemento para el pelo', 'Dar suplementos junto con las comidas', TIMESTAMP '2023-05-12 17:00:00');
INSERT INTO RecetasMedicas ( ID_mascota, ID_personal, Peso, Medicamentos_recetados, Indicaciones_generales, Fecha) VALUES (2, 3, 30, 'Vacuna antirrábica', 'Vacunar una vez al año', TIMESTAMP '2023-05-11 15:00:00');
INSERT INTO RecetasMedicas ( ID_mascota, ID_personal, Peso, Medicamentos_recetados, Indicaciones_generales, Fecha) VALUES (5, 2, 10, 'Desparasitante', 'Administrar cada 6 meses', TIMESTAMP '2023-05-13 11:00:00');

INSERT INTO Ventas ( ID_producto, ID_personal, Cantidad_vendida, Subtotal, Total, Fecha_venta) VALUES (1, 2, 10, 150, 150, TIMESTAMP '2023-05-12 10:00:00');
INSERT INTO Ventas ( ID_producto, ID_personal, Cantidad_vendida, Subtotal, Total, Fecha_venta) VALUES (3, 1, 1, 5000, 5000, TIMESTAMP '2023-05-12 11:00:00');
INSERT INTO Ventas ( ID_producto, ID_personal, Cantidad_vendida, Subtotal, Total, Fecha_venta) VALUES (2, 3, 5, 50, 50, TIMESTAMP '2023-05-12 12:00:00');
INSERT INTO Ventas ( ID_producto, ID_personal, Cantidad_vendida, Subtotal, Total, Fecha_venta) VALUES (4, 4, 20, 400, 400, TIMESTAMP '2023-05-12 13:00:00');
INSERT INTO Ventas ( ID_producto, ID_personal, Cantidad_vendida, Subtotal, Total, Fecha_venta) VALUES (5, 5, 10, 300, 300, TIMESTAMP '2023-05-12 14:00:00');

INSERT INTO Mascotas ( ID_propietario, Nombre, Tipo, Raza, Fecha_nacimiento, Color, Sexo, Imagen) VALUES (1, 'Fido', 'Perro', 'Labrador', DATE '2018-05-11', 'Amarillo', 'M', '/imagenes/mascotas/fido.jpg');
INSERT INTO Mascotas ( ID_propietario, Nombre, Tipo, Raza, Fecha_nacimiento, Color, Sexo, Imagen) VALUES (2, 'Luna', 'Perro', 'Pastor Alemán', DATE '2020-05-11', 'Negro y fuego', 'H', '/imagenes/mascotas/luna.jpg');
INSERT INTO Mascotas ( ID_propietario, Nombre, Tipo, Raza, Fecha_nacimiento, Color, Sexo, Imagen) VALUES (3, 'Toby', 'Perro', 'Bulldog Inglés', DATE '2016-05-12', 'Blanco y atigrado', 'M', '/imagenes/mascotas/toby.jpg');
INSERT INTO Mascotas ( ID_propietario, Nombre, Tipo, Raza, Fecha_nacimiento, Color, Sexo, Imagen) VALUES (4, 'Bella', 'Gato', 'Siames', DATE '2021-05-12', 'Lynx Point', 'H', '/imagenes/mascotas/bella.jpg');
INSERT INTO Mascotas ( ID_propietario, Nombre, Tipo, Raza, Fecha_nacimiento, Color, Sexo, Imagen) VALUES (5, 'Rocky', 'Perro', 'Poodle', DATE '2019-05-13', 'Blanco', 'M', '/imagenes/mascotas/rocky.jpg');
