# Generated by Django 4.2.1 on 2023-05-16 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expedientes',
            fields=[
                ('ID_expediente', models.AutoField(db_column='ID_expediente', primary_key=True, serialize=False)),
                ('Nombre_mascota', models.CharField(max_length=30)),
                ('Edad', models.IntegerField()),
                ('Sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('Raza', models.CharField(max_length=30)),
                ('Color', models.CharField(max_length=20)),
                ('Historial_clinico', models.TextField(blank=True, null=True)),
                ('Cirugias', models.TextField(blank=True, null=True)),
                ('Tratamientos', models.TextField(blank=True, null=True)),
                ('Fecha_ingreso', models.DateTimeField()),
                ('Fecha_egreso', models.DateTimeField(blank=True, null=True)),
                ('Diagnostico', models.TextField(blank=True, null=True)),
                ('Esquema_vacunacion', models.TextField(blank=True, null=True)),
                ('Alergias', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'EXPEDIENTES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('ID_producto', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_producto', models.CharField(max_length=50)),
                ('Area', models.CharField(max_length=30)),
                ('Caracteristicas', models.TextField()),
                ('Precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Cantidad_inventario', models.IntegerField()),
                ('Fecha_caducidad', models.TextField()),
                ('Productos_descuento', models.IntegerField()),
                ('Marca_producto', models.CharField(blank=True, max_length=50, null=True)),
                ('Presentacion', models.CharField(blank=True, max_length=30, null=True)),
                ('Fecha_compra', models.TextField()),
            ],
            options={
                'db_table': 'INVENTARIO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('ID_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Tipo', models.CharField(max_length=30)),
                ('Raza', models.CharField(max_length=30)),
                ('Fecha_nacimiento', models.DateField()),
                ('Color', models.CharField(blank=True, max_length=20, null=True)),
                ('Sexo', models.CharField(max_length=1)),
                ('Imagen', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'MASCOTAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('ID_nomina', models.AutoField(primary_key=True, serialize=False)),
                ('Horas_trabajadas', models.IntegerField()),
                ('Horas_extras', models.IntegerField(default=0)),
                ('Retardos', models.IntegerField(default=0)),
                ('Faltas', models.IntegerField(default=0)),
                ('Empleado_del_mes', models.BooleanField(default=False)),
                ('Fecha_pago', models.DateTimeField()),
                ('Tipo_pago', models.CharField(max_length=20)),
                ('Salario_NETO', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'NOMINA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id_personal', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_personal', models.CharField(blank=True, choices=[('Medicos veterinarios', 'Medicos veterinarios'), ('Recepcionista', 'Recepcionista'), ('Encargado de acuario', 'Encargado de acuario'), ('Encargado de accesorios', 'Encargado de accesorios'), ('Encargado de articulos generales', 'Encargado de articulos generales'), ('Encargado de estetica', 'Encargado de estetica')], max_length=35, null=True)),
                ('cedula_profesional', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('especialidad', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_completo', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('numero_telefonico', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=100)),
                ('turno', models.CharField(choices=[('M', 'M'), ('V', 'V')], max_length=2)),
                ('horario', models.CharField(choices=[('8-4', '8-4'), ('1-9', '1-9')], max_length=10)),
                ('salario_neto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('curp', models.CharField(max_length=18, unique=True)),
            ],
            options={
                'db_table': 'PERSONAL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Propietarios',
            fields=[
                ('ID_propietario', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Telefono', models.CharField(max_length=20)),
                ('Direccion', models.CharField(max_length=100)),
                ('Mascotas', models.IntegerField(blank=True, null=True)),
                ('Correo_electronico', models.EmailField(max_length=50)),
            ],
            options={
                'db_table': 'PROPIETARIOS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'PROVEEDORES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecetasMedicas',
            fields=[
                ('ID_receta', models.AutoField(primary_key=True, serialize=False)),
                ('Peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Medicamentos_recetados', models.TextField()),
                ('Indicaciones_generales', models.TextField(blank=True, null=True)),
                ('Fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'RECETASMEDICAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('ID_venta', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad_vendida', models.IntegerField()),
                ('Subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Fecha_venta', models.DateTimeField()),
            ],
            options={
                'db_table': 'VENTAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datecompleted', models.DateTimeField(blank=True, null=True)),
                ('important', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('nombre_propietario', models.CharField(max_length=100)),
                ('telefono_propietario', models.CharField(max_length=100)),
                ('direccion_propietario', models.CharField(max_length=100)),
                ('historial', models.CharField(max_length=100)),
                ('cirugias', models.CharField(max_length=100)),
                ('tratamientos', models.CharField(max_length=100)),
                ('fechas_egreso', models.CharField(max_length=100)),
                ('diagnostico', models.CharField(max_length=100)),
                ('esquema_vacunas', models.CharField(max_length=100)),
                ('alergias', models.CharField(max_length=100)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
